name: Build and push image
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: pangzineng/Github-Action-One-Click-Docker@v1.1.1
      with:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      env:
        DOCKER_USERNAME: vlkoti
        DOCKER_NAMESPACE: vlkoti
        DOCKER_IMAGE_NAME: mible
