name: Build and push image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build image
        run: |
          docker login -u vlkoti -p ${{ secrets.DOCKER_PASSWORD }}
          make push
